### ISSUE TITLE
missing: 1.17.1

### ISSUE THREAD

**Issue by thepwagner** [renovatebot/docker-go#93]
Why didn't https://github.com/renovatebot/docker-go/blob/main/Dockerfile#L2 get bumped when  the go [`1.17.1` release](https://hub.docker.com/layers/golang/library/golang/1.17.1/images/sha256-f07e3cc6655731510e17265852380861aaa77f23c17c94c896f948e544d2f0cf?context=explore) happened?

AFAICT through a few levels of `extends`, it should be matched by [this rule](https://github.com/renovatebot/.github/blob/ae87eb94326f99f859f6e0b8707c69f5642e691a/default.json#L112).
* https://github.com/renovatebot/docker-go/blob/main/renovate.json
* https://github.com/renovatebot/presets-internal/blob/master/docker-images.json
* https://github.com/renovatebot/.github/blob/main/default.json

**Comment by viceice** [comment]
Should now come in a few hours. Did a manual renovate trigger.

@rarkins is the app too optimistic about runs?

**Comment by rarkins** [comment]
What do you mean by optimistic?

**Comment by viceice** [comment]
Ok, the release was two days ago, and renovate seems to run weekly because of no changes for a week

**Comment by viceice** [comment]
Fixed in 50c2831dacbaa0dd4b31cffd27a895d731022bfe

**Comment by viceice** [comment]
Can we add our repos to an exclude list, so renovate won't reduce it's schedule to weekly?
